#!/bin/bash

prev_val=$1
while getopts "h" opt; do
    case $opt in
        h)	echo "Show a unicolor pane in fullscreen, based on given exit code and/or given hex color"
            echo "Usage: _feedback EXIT_CODE [HEX COLOR]"
            return 0;;
        *)	echo "invalid option '$opt'"
                exit 1;;
        esac
    done
    shift $((OPTIND -1))
if [[ -n $2 ]];then
    color="#$2"
else
    if [[ $prev_val -eq 0 ]];then
        color="#3CA73A"
    else
        color="#B44444"
    fi
fi
convert -size 16x9 xc:$color jpg:- | feh -Z -F - >& /dev/null
