#!/bin/bash
# Modify volume of sink input linked to focused window

if [[ $1 = '-h' ]]; then
	echo 'Usage: app_vol MODIFIER'
	echo 'Modify volume of the currently focused window'
	echo 'Example: app_vol +5%'
	exit 0
fi

index=($(audio_pindex))
echo "index: $index"
if [[ "${index[@]}" != '-1' ]]; then
	# Sometimes, inputs are indistinguishables. Safe bet is to affect all of them
	if [[ "${#index[@]}" -gt 1 ]]; then
		multi_input=true
	else
		multi_input=false
	fi
	for line in "${index[@]}"; do
		pactl set-sink-input-volume $line $1
		read -r vol name <<< $(
			pactl list sink-inputs | perl -00n -e "if(/Sink Input #$line/) {" \
			-e '/Volume.*?(\d+%)/; print "$1 ";' \
			-e '/media.name = "(.*)"/; print $1; }'
		)
		if $multi_input; then
			total_vol+=("[$name] $vol")
		else
			title="'$name'"
			total_vol="$vol"
		fi
	done
	set -- "${total_vol[@]}"
	IFS=$'\n'
	old_notif=$(grep '[0-9]' /tmp/app_vol_id || echo 0)
	notify-send -r $old_notif -p -t 1000 $name "$*" > /tmp/app_vol_id
fi

