#!/bin/bash
# Modify volume of sink input linked to focused window

if [[ $1 = '-h' ]]; then
	echo 'Usage: app_vol MODIFIER'
	echo 'Modify volume of the currently focused window'
	echo 'Example: app_vol +5%'
	exit 0
fi

index=($(audio_pindex))
echo "index: $index"
if [[ "${index[@]}" != '-1' ]]; then
	# Sometimes, inputs are indistinguishables. Safe bet is to affect all of them
	for line in "${index[@]}"; do
		pactl set-sink-input-volume $line $1
		vol=$(pacmd list-sink-inputs | grep -P -A5 "index: $line" | tail -n1 | awk -F"/" '{print $2}' | sed 's/ //g')
		echo "vol: $vol"
		total_vol="$total_vol $vol"
	done
	notify-send -t 500 "$total_vol"
fi
