#!/bin/bash
# Compacts input by displaying multiple input lines on a single output line

SEPARATOR=
COLUMNS=true


read -rd '' helpmsg <<EOF
Takes multi-line input from STDIN and prints COMPRESSION input lines
per output line. Breaks if your text contains the separator (ascii 31 by default)

\x1b[1mUsage\x1b[m: cat myfile.txt | compact [\x1b[36mOPTION\x1b[m]... \x1b[36mCOMPRESSION\x1b[m

\x1b[1mParameters\x1b[m:
  -h  show this message and exit
  -c  disables columnized output
  -s  SEP changes the separator. Only works with single characters
EOF

while getopts "hcs:" opt; do
    case $opt in
        h) echo -e "$helpmsg" >&2
           exit 0;;
        c) COLUMNS=false;;
        s) SEPARATOR=$OPTARG;;
        *) echo "invalid option '$opt'. Try -h for help"
           exit 1;;
        esac
    done
shift $((OPTIND -1)) 

if [[ $# -eq 0 ]] || [[ "$1" =~ ^[^0-9]+$ ]]; then
    echo -e "$helpmsg" >&2
    exit 1
fi

# Reads stdin, NULs newlines, recursively replace every $1th nul by newline,
# turns NULs into SERPARATOR for column
output=$(cat - | tr '\n' '\0' | sed "s/\x0/\n/$1;P;D" | tr '\0' $SEPARATOR)
if $COLUMNS; then
    echo "$output" | column -t -s $SEPARATOR
else
    echo "$output" | tr $SEPARATOR ' '
fi
