#!/bin/bash

# Fzf MENU, using alacritty
msg="Usage: vals | fmenu [OPTIONS] [-- QUOTED_FZF_OPTIONS..] | something
Select something from STDIN and send it to STDOUT, in a popup window
Example: dmenu_path | fmenu "'"--preview='"'which {}'"'"'" | xargs sh -c
  -h        Display help
  -b        Display window border (Only without -i)
  -f        Don't make window floating
  -d        Specify dimensions in characters: 200x14 (Only without -i)
  -I        Do not use alacritty IPC to create a new window
  --delay   With IPC, how many secs between each check to see if selection
            is over (0.2s by default)"
DECORATIONS=none
DIMENSIONS=''
FLOATING=FLOATING
IPC=true

ARGS=$(getopt --options 'hbfId:' --longoptions 'help,delay:' -- "$@" || exit 1)
exitcode=$?
if [[ $exitcode -ne 0 ]]; then
	exit $exitcode
fi

eval set -- "$ARGS"
while true; do
	case "$1" in
		'-h'|'--help') 
			if tty >/dev/null; then
				echo "$msg"
			else
				notify-send "$msg"
			fi
			exit 0;;
		'-b') 
			DECORATIONS=full
			shift
			continue;;
		'-f') 
			FLOATING=Alacritty
			shift
			continue;;
		'-I') 
			IPC=false
			shift
			continue;;
		'-d') 
			x=${2%x*}
			y=${2#*x}
			DIMENSIONS="window.dimensions.columns=$x window.dimensions.lines=$y"
			shift 2
			continue;;
		'--delay') 
			DELAY=$2
			shift
			continue;;
		'--') 
			shift
			break;;
	esac
done

# ========== IPC ver ==========
if $IPC; then
	# Create pipe to share PID, since alacritty's IPC means the creation job is
	# over the moment the terminal spawns, so we need to wait for the spawned
	# sh instance to finish instead
	rm /tmp/fmenu 2>/dev/null
	mkfifo /tmp/fmenu 2>/dev/null
	alacritty msg create-window --class $FLOATING -e sh -c 'IFS=;echo $$ > /tmp/fmenu;'" fzf $* < /proc/$$/fd/0 > /proc/$$/fd/1"
	pid=$(cat /tmp/fmenu)
	while [[ -d /proc/$pid ]]; do
		sleep 0.2
	done

# ==========  Non-IPC ver ==========
else
	alacritty -o window.decorations=$DECORATIONS $DIMENSIONS --class $FLOATING -e sh -c " fzf -1 $* < /proc/$$/fd/0 > /proc/$$/fd/1"
fi
