#!/bin/sh
# Offers between sensible keyboard layouts
locale=$(printf 'leyaourt\nus(altgr-intl)\nfr' | fmenu -I -d 65x10 -- "+m '--prompt=Layout: ' --preview=")
#locale=$(printf 'leyaourt\nus(altgr-intl)\nfr' | dmenu)
if [ -n "$locale" ]; then
	setxkbmap $locale
	notify-send -t 1500 "Locale set to $locale"
fi
