#!/bin/bash
# Switches between AZERTY and QWERTY keyboard modes
if (setxkbmap -print | grep azerty); then
    setxkbmap 'us(altgr-intl)'
    # Absolute beast of a layout. No dead keys without altgr, can you believe that?!
    notify-send --expire-time=750 "locale" "QWERTY (us(altgr-intl))"
else
	setxkbmap fr
    notify-send --expire-time=750 "locale" "AZERTY (fr)"
fi
