#!/bin/bash
# Converts markdown to HTML using formatting I find saner.
# Saves the hassle of including these tags everytime, and hides the
# ghoulish cmark-gfm + sed call
[[ $# -eq 0 ]] && [[ -t 0 ]] && exit 1
[[ $1 = "-k" ]] && RM_HTML=false && shift

fname={1:-nameless_md}

cat > "tmp_$fname" <<EOF
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/monokai-sublime.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
<style>
code {
    max-width: 50%;
}
</style>

EOF
cat ${1:--} >> "tmp_$fname"
cat >> "tmp_$fname" <<< "<script>hljs.highlightAll();</script>"

cmark-gfm -e tasklist --unsafe "tmp_$fname" > "tmp_$fname.html"
rm "./tmp_$fname"
sed -i 's/disabled=""//' "tmp_$fname.html"
firefox "tmp_$fname.html"
$RM_HTML && $(sleep 2 && rm "./tmp_$fname.html")& 
