#!/bin/bash
LAYOUT_PATH=~/ukext.png
existing=$(ps axo pid,command | grep "[f]eh.*QWERTY_LAYOUT" | tail -n 1 | awk '{print $1}')
echo $existing
if [[ -n $existing ]]; then
    kill $existing
else
    i3-msg focus output left
    feh $LAYOUT_PATH -^ QWERTY_LAYOUT & sleep 0.15
    i3-msg focus output right
fi
