#!/bin/bash
# Recursive rg

read -d '' helpmsg <<EOF
Usage: rrg [OPTION]... PATTERN1 PATTERN2...
Recursive ripgrep, find matches in files with matches in files with matches in fi...
Example: rrg standard_offer category_id execute 'please select'

Parameters:
  -c            forces colored output
  -C CONTEXT    changes the number of lines of context (default is 5)
EOF

counter=0
files=""
color=auto
context=5

while getopts "hcC:" opt; do
    case $opt in
        h)  echo "$helpmsg"
            exit 0;;
        c)  color=always;;
        C)  context=${OPTARG};;
        *)  echo -e"invalid option '$opt'\n"
            echo "$helpmsg"
            exit 1;;
        esac
    done
    shift $((OPTIND -1))

for pattern in "$@"; do
    ((counter ++))
    if [[ $counter -eq $# ]]; then
        rg --color=$color -C $context "$pattern" $files
    else
        files=$(rg -l "$pattern" $files)
    fi

done
