#!/bin/bash
paths=
IFS='/' 
if [[ ${#1} -gt 1 ]]; then
    for path in $(dirname "$*"); do
        paths+=$(cut -c1-2 <<< $path)/
    done
    paths+=$(basename "$*")
    sed "s@$HOME@~@" <<< $paths
else
    echo '/'
fi
